# Enable/Disable Built-In Features
aha_board: false
question_board: false

# Custom Sidebar Links to External Sites.
# ----------------------------------------
# Must be an array.  Start with a dash on its own line.
# Then indent and provide label, url, and fa icon (optional)
# The default icon is fa-cloud.
# sidebar:
sidebar:
  
  -
    label: Syllabus
    url: 'https://www4.kellogg.northwestern.edu/syllabus/syllabus_files/KIEI-924-5-80_Fall2016.pdf'
    icon: fa-list-ol
  
